### PR TITLE
add theoneprobe provider for panels [wip]

### PR DESCRIPTION
**Pull request by lublak**
also fixes: https://github.com/dannydjdk/Tiny-Redstone/issues/32

### CODE REVIEW

**Comment by dannydjdk** [comment]
Oops! I didn't mean to mark it ready to review.

**Comment by dannydjdk** [comment]
Looks great so far!

I think I'm going to work on something like the vanilla BlockPos class for cell positions. There are many instances in my code where I'm doing things like this:
             int row = Math.round((float) (x * 8f) - 0.5f);
             int cell = Math.round((float) (z * 8f) - 0.5f);
             int cellIndex = (row * 8) + cell;
Probably doesn't need to change the direction you're going right now, but something to possibly consider for the future.

**Comment by lublak** [comment]
A few things still need to be done, though. Well actually only add a addProbeInfo method to each component class.
And here and there a little tidy up.
Basically I would design it like TOP standard methods for redstone circuits.

**Comment by lublak** [comment]
it goes ahead
grafik
grafik

**Comment by lublak** [comment]
some notes for me:
grafik
fix with: https://github.com/McJtyMods/TheOneProbe/pull/453
or:

if detect edge power (> 0) with: `world.getRedstonePower(pos, probeHitData.getSideHit().getOpposite());` do not call IPanelCellProbeInfoProvider, etc..

**Comment by dannydjdk** [comment]
Hopefully, my last commit doesn't mess with you too much. I tried to avoid changes that would conflict with what you're doing.
My next commit will involve circuit covers which may require a small change regarding One Probe support. Basically, we would be disabling the custom info when a cover is installed.

**Comment by lublak** [comment]
@dannydjdk 
It was fine, just a conflict file with 6 errors that I had to correct manually. It's just always confusing.
And yes, when cover is installed, no more info should be displayed. (except of course the standard information)

**Comment by dannydjdk** [comment]
How difficult would it be to put the PanelCellPos code in a separate pull request? One feature I want to look into soon is vertical placement, and that feature will be quite useful. I can try to extract it myself if you want to stay focused on moving forward with TOP.

**Comment by lublak** [comment]
@dannydjdk i can do it tomorow. No problem.
Additional i would add the PosInPanelCell class.
Today I had longer work (because next week I'm on holiday) and also evening studies.
So today I just did the merge.
I just don't know how to do it with the current pull request.
There will probably be conflicts again

**Comment by dannydjdk** [comment]
No rush. I won't have a lot of time weekend.

**Comment by lublak** [comment]
@dannydjdk I think I can even have everything ready tomorrow. Then you can merge the complete pull request if you like.
Is just a "is from the top" fix and a bit of clean up.

**Comment by lublak** [comment]
@dannydjdk is there anything else you'd like to have in there?

**Comment by dannydjdk** [comment]
How well does it perform? Have you noticed any lag when quickly scanning over a lot of components? If so, it might be a good idea to only show the component details if you have a wrench or component in your hand. That's how Chisels & Bits works. If there's no performance issues, then I think it would be nicer if it just showed all the time.

**Comment by lublak** [comment]
@dannydjdk 
I don't notice any drop in performance myself, but I also have a relatively powerful PC.
I can add a config option, then everyone can decide for themselves. But generally I would realise it via tags in addition to config:
tinyredstone:items/measuring_device

Config options could be:
Normal (as it currently works)
Extended (only if you press shift)
Device (only if you hold an item in the measuring_device tag)

**Comment by dannydjdk** [comment]
If you think it's something you could do fairly quickly, you could use this request. Otherwise, a second request could be nice. I'll leave it up to you.

**Comment by lublak** [comment]
Is actually already almost done xD.
Has only a mistake crept in.
Thought it was more complicated.
My last commit includes it.
Means: Just clean up and test a bit.

**Comment by lublak** [comment]
I think the code can be tweaked here and there, but for now it should be okay.
I have also fixed the bug with raytracing.

**Comment by dannydjdk** [comment]
Very nice!
How do you use debug mode? That information could be really useful!

**Comment by lublak** [comment]
you can use the creative probe.

**Comment by dannydjdk** [comment]
I swear I tried the creative probe and it didn't work, but it works now. 🤓

**Comment by lublak** [comment]
What can be is that you have disabled the trial support in the settings. Currently it does not show any debug information. But would perhaps make sense that I change that in debug mode the data are displayed. Possibly also that the cover is ignored. But I prefer to wait xD. Let's see what you still change everything.

**Pull request merged**
